/**
 * Scenario 1: Gated Workflow
 *
 * Tests the gated workflow with the delta team (orchestrator + gates + workflow template).
 * Verifies: workflow stages, dependency chain, task generation from template.
 *
 * NOTE: Full workflow completion (all stages completing end-to-end) depends on
 * LLM decisions and subagent delegation. This test verifies that the workflow
 * template generates the correct task chain on run start, and that the state
 * is properly persisted. Full completion is a best-effort check.
 */

import { describe, it, expect, beforeAll } from "vitest";
import { askAgent } from "../helpers/openclaw.js";
import {
  readRunState,
  readActivity,
  getBroadcastPath,
} from "../helpers/state.js";
import { EventWatcher } from "../helpers/watcher.js";
import { cleanAllState } from "../helpers/reset.js";

describe("Scenario 1: Gated Workflow", () => {
  beforeAll(async () => {
    await cleanAllState();
  });

  it("1.1: workflow template generates task chain on run start", async () => {
    const watcher = new EventWatcher(getBroadcastPath());

    try {
      // Send message requesting gated workflow
      const agentPromise = askAgent(
        "Have the delta team implement a user authentication feature. " +
          "Use the Agent Teams plugin to coordinate this.",
        { timeout: 120_000 },
      );

      // 1. Wait for run_started (LLM inference can take 30-60s on fresh session)
      const runEvent = await watcher.expectEvent("run_started", {
        timeout: 60_000,
      });
      expect(runEvent.team).toBe("delta");

      // 2. Wait for main agent response (ensures all state writes are done)
      const response = await agentPromise;
      expect(response.meta.error).toBeUndefined();

      // 3. Read state — check workflow stages and dependencies
      const runState = readRunState("delta");
      expect(runState).not.toBeNull();
      expect(runState!.status).toBe("WORKING");

      const tasks = runState!.tasks;
      expect(tasks.length).toBeGreaterThanOrEqual(2);

      // Check for workflow_stage on tasks (auto-generated by template engine)
      const stagedTasks = tasks.filter((t) => t.workflow_stage);
      if (stagedTasks.length >= 2) {
        const stages = stagedTasks.map((t) => t.workflow_stage);

        // Verify stages include expected workflow stages
        const hasImplement = stages.some(
          (s) => s?.toLowerCase().includes("implement"),
        );
        const hasTest = stages.some(
          (s) => s?.toLowerCase().includes("test"),
        );
        const hasReview = stages.some(
          (s) => s?.toLowerCase().includes("review"),
        );

        // At minimum, some workflow stages should exist
        expect(hasImplement || hasTest || hasReview).toBe(true);

        // Check dependency chain: later stages should depend on earlier ones
        const dependentTasks = tasks.filter(
          (t) => t.depends_on && t.depends_on.length > 0,
        );
        if (dependentTasks.length > 0) {
          expect(dependentTasks.length).toBeGreaterThan(0);

          // Blocked tasks should start in BLOCKED state
          const blockedTasks = tasks.filter((t) => t.status === "BLOCKED");
          expect(
            blockedTasks.length +
              tasks.filter((t) => t.status === "PENDING").length,
          ).toBeGreaterThan(0);
        }
      }

      // 4. Verify activity log has basic events
      const activity = readActivity("delta");
      const types = activity.map((e) => e.type);
      expect(types).toContain("run_started");

      // Workflow template should produce a workflow_stage_advanced event
      if (stagedTasks.length >= 2) {
        expect(types).toContain("workflow_stage_advanced");
      }
    } finally {
      watcher.close();
    }
  });

  it("1.2: dependency chain in activity log", async () => {
    const activity = readActivity("delta");
    const types = activity.map((e) => e.type);

    // Basic lifecycle events should be present from 1.1
    expect(types).toContain("run_started");

    // task_created should exist (either from workflow template or LLM)
    const hasTaskEvents =
      types.includes("task_created") ||
      types.includes("workflow_stage_advanced");
    expect(hasTaskEvents).toBe(true);

    // Check for dependency/workflow-related events
    const workflowEvents = activity.filter(
      (e) =>
        e.type === "dependency_resolved" ||
        e.type === "workflow_stage_advanced" ||
        e.type === "deliverable_added" ||
        e.type === "dependency_blocked" ||
        e.type === "dependency_cascaded",
    );

    // If workflow events exist, verify their structure
    if (workflowEvents.length > 0) {
      for (const event of workflowEvents) {
        expect(event.team).toBe("delta");
        expect(event.agent).toBeDefined();
        expect(event.timestamp).toBeGreaterThan(0);
      }
    }

    // Verify temporal ordering — events should be in timestamp order
    for (let i = 1; i < activity.length; i++) {
      expect(activity[i].timestamp).toBeGreaterThanOrEqual(
        activity[i - 1].timestamp,
      );
    }
  });
});
